### ISSUE TITLE
Replace k8s.gcr.io with registry.k8s.io

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/k8s-cluster-api-provider#412]
As [k8s.gcr.io redirects to registry.k8s.io now](https://kubernetes.io/blog/2023/03/10/image-registry-redirect/) also the last occurrences need to be replaced. Also this obsoletes the [fixup script](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/terraform/files/bin/fixup_k8sregistry.sh).

## Tasks

- [x] Replace k8s.gcr.io with registry.k8s.io
- [x] Remove fixup script
- [x] Test if all supported versions still work

**Comment by jschoone** [comment]
Hi @cah-hbaum, sounds great! Could you create a PR then we can merge it

**Comment by cah-hbaum** [comment]
Was already merged in #422 by @garloff.

**Comment by jschoone** [comment]
Ah thanks! I added the relation and close this issues with this comment.
